pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label!=hold-off-merging
      - status-success=build (10.x)
      - status-success=build (12.x)
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
